import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dental Billing Aid",
  description: "Generated by create next app",
  icons: {
    icon: "/images/fav.png",
  },
};

import Header from "./components/Header";
import Footer from "./components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 dark:bg-black overflow-x-hidden`}>
        <Header />
        <main className="max-w-7xl mx-auto w-full px-4 min-h-[80vh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
